# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'iOSStudy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSStudy
  pod 'SDWebImage'
  pod 'Aspects'
  pod 'YYKit'

  target 'iOSStudyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSStudyUITests' do
    # Pods for testing
  end

end
