# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'iOSStudy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSStudy
  pod 'SDWebImage'
  pod 'Aspects'
  pod 'YYKit'
  pod 'Masonry'
  pod 'FMDB'
  pod 'AFNetworking'
#  pod 'UITableView+FDTemplateLayoutCell'
  pod 'PLCrashReporter'
  pod 'KSCrash'
  pod 'DoraemonKit'
  pod 'Texture'
  pod 'IGListKit'
  pod 'KSCrash'
  pod 'PLCrashReporter'

  target 'iOSStudyTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'OCMock'
  end

  target 'iOSStudyUITests' do
    # Pods for testing
  end

end
